# Generated by Django 4.1 on 2023-04-24 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_userprofile_desc_userprofile_gexing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="image",
            field=models.ImageField(
                default="image/default.png",
                upload_to="images/%Y/%m/",
                verbose_name="用户头像",
            ),
        ),
    ]
