# Generated by Django 4.1 on 2023-04-25 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_sidebar_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="sidebar",
            name="is_hot",
            field=models.BooleanField(default=False, verbose_name="是否热门"),
        ),
    ]
