# Generated by Django 4.1 on 2023-04-26 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_sidebar_is_hot"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sidebar",
            name="is_hot",
        ),
        migrations.AddField(
            model_name="sidebar",
            name="pv",
            field=models.IntegerField(default=0, verbose_name="浏览量"),
        ),
    ]
